### ISSUE TITLE
Any way to order the problems? 

### ISSUE THREAD

**Issue by zkghost** [prius/leetcode-anki#23]
I've found the most helpful thing for me so far is using curated/organized lists, like [this one](https://seanprashad.com/leetcode-patterns/).

I started manually making cards and it is a pain, so your tool seems great! But I am concerned if Anki is just going to randomly throw all 25XX problems at me, it won't be as effective. 

Is there any way (via this or in Anki) to encourage/constrain the cards or their ordering?

**Comment by prius** [comment]
Hi @zkghost 

There is a support for a sort field in genanki library https://github.com/kerrickstaley/genanki#sort_field

However, I played around with it for a few hours, and it didn't seem to work.

There is an open issue for this https://github.com/prius/leetcode-anki/issues/10.

So yeah, I don't think there is a way to organize those cards in any particular order unless I'm missing something.

**Comment by gh4n** [comment]
@zkghost I suggest setting the sort field as frequency in browse section and then manually selecting the top `n` cards for your purpose and putting them into a new deck. You may want to refine this new deck further by filtering for mediums or certain topics.

**Comment by zkghost** [comment]
Yeah, I think I am just going to manually create cards as I solve the problems following the leetcode-patterns list and add the order number to the cards and sort by that.
