### ISSUE TITLE
How to add solutions?

### ISSUE THREAD

**Issue by raakasf** [prius/leetcode-anki#33]
This repo is really awesome and just what I was doing for myself.
I just have a question about adding my own solutions to the "back" card. I managed to add the field but it's not the back. And I don't see the discuss and solutions card.. could you help me with this?

**Comment by lzx404243** [comment]
I think you can add a new note type that has all the fields in the original note type, PLUS an additional "solution" field. Then you can change all the imported cards to the new note type. These can all be done in the Anki card browser view.

**Comment by VivekThazhathattil** [comment]
@lzx404243 Thank you!
